### PR TITLE
Add to cart

### PR DESCRIPTION
**Pull request by luandang4**
## Related Tickets
- [#43529](https://edu-redmine.sun-asterisk.vn/issues/43529)

## WHAT (optional)
- đăng nhập role user
- click mua hàng thì giỏ hàng +1 sản phẩm

## HOW
- Session
- Check residual quantity

## Evidence (Screenshot or Video)
Screenshot from 2021-12-02 09-24-56
Screenshot from 2021-12-02 09-25-17

### CODE REVIEW

**Comment by luandang4** [comment]
Ready

**Review by trananhminh910 — APPROVED** [review]

**Comment by luandang4** [comment]
Ready

**Comment by luandang4** [comment]
Ready

**Comment by luandang4** [comment]
Ready

**Comment by luandang4** [comment]
Ready

**Review by ghost — COMMENTED** [review]
merged

**Pull request merged**
